name: Test Address Sanitizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9
      
    - name: Install nextest
      uses: taiki-e/install-action@nextest
      
    - name: Install Ubuntu Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: llvm
        version: 1.0
      if: matrix.os == 'ubuntu-latest'

    - name: Install MacOS Dependencies
      run: |
        brew update
        brew install llvm || echo "This step will fail because of python@3.11 so we force link and ignore the error"
        brew link --overwrite python@3.11
      if: matrix.os == 'macos-latest'  

    - name: Install nightly rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src

    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run address-sanitizer tests
      run: cargo +nightly xtask address-sanitizer
      env:
        RUST_BACKTRACE: full
        RUST_LOG: debug
        RUSTC_WRAPPER: sccache
